title: Mixed-Precision Iterative Refinement on GPUs
description: High-performance mixed-precision linear solvers using CUDA

theme: just-the-docs

url: https://olebo.github.io
baseurl: /mixed-precision-iterative-refinement-gpu

search_enabled: true             # Enable or disable the site search

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"

nav_sort: case_insensitive

color_scheme: dark

plugins:
  - jekyll-default-layout


# Math support
kramdown:
  math_engine: mathjax

aux_links:                    # Aux links for the upper right navigation
  Repository: https://github.com/OleBo/mixed-precision-iterative-refinement-gpu

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true

# Color scheme supports "light" (default) and "dark"
color_scheme: dark