title: Mixed-Precision Iterative Refinement on GPUs
description: High-performance mixed-precision linear solvers using CUDA

theme: just-the-docs

url: https://olebo.github.io
baseurl: /mixed-precision-iterative-refinement-gpu

search_enabled: true
nav_sort: case_insensitive

color_scheme: dark

# Math support
kramdown:
  math_engine: mathjax

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
